.ORIG x3000

;;YOUR CODE STARTS HERE
		AND R1, R1, #0
NEXTT
		LD R6, STRING_START
		LDI R0, STRING_START
		BRz TRAPP
		LD R5, ASCII_NEG_ZERO
		ADD R5, R5, R0
		BRn OUTT
		LD R5, ASCII_NINE
		NOT R5, R5
		ADD R5, R5, #1
		ADD R5, R5, R0
		BRnz NUMMM

OUTT
		LD R5, ASCII_NEG_ASTERISK
		ADD R5, R5, R0
		BRz RRR
		ADD R0, R0, #0
		OUT
		ADD R6, R6, #1
		ST R6, STRING_START
		BRnzp NEXTT

RRR
		ADD R6, R6, #-1
		ST R6, SAVE_R66
		LD R5, SAVE_R66
		LD R3, SAVE_NUM
		ADD R3, R3, #-1
NNN		LD R2, SAVE_R6
		NOT R2, R2
		ADD R2, R2, #1
		LDI R0, SAVE_R6
		OUT
		ADD R2, R2, R5
		BRz DECRE
		LD R2, SAVE_R6
		ADD R2, R2, #1
		ST R2, SAVE_R6
		BRnzp NNN
DECRE
		ADD R3, R3, #-1
		BRp NNN
		LD R6, SAVE_R6
		ADD R6, R6, #2
		ST R6, STRING_START
		BRnzp NEXTT

NUMMM
		ADD R0, R0, #-15
		ADD R0, R0, #-15
		ADD R0, R0, #-15
		ADD R0, R0, #-3
		BRz ZEROO
		ST R0, SAVE_NUM
		ADD R6, R6, #1
		ST R6, SAVE_R6
		ST R6, STRING_START
		BRnzp NEXTT

ZEROO
NTT		ADD R6, R6, #1
		ST R6, STRING_START
		LDI R0, STRING_START
		LD R4, ASCII_NEG_ASTERISK
		ADD R4, R4, R0
		BRnp NTT
		ADD R6, R6, #1
		ST R6, STRING_START
		BRnzp NEXTT


		
TRAPP
		TRAP x25


ASCII_ZERO		.FILL x0030		;ASCII value of Zero
ASCII_NINE		.FILL x0039		;ASCII value of Nine
ASCII_NEG_ASTERISK   	.FILL xFFD6  		;negative of ascii value of *
ASCII_NEG_ZERO    	.FILL xFFD0		;negative of ascii value of 0
STRING_START 		.FILL x4000		;starting address of string
SAVE_R6			.BLKW #1
SAVE_NUM		.BLKW #1
SAVE_R66		.BLKW #1
.END
